### ISSUE TITLE
NotNull-db

### ISSUE THREAD

**Issue by felixfilipi** [felixfilipi/Beli-Desain#18]
All db-query should not null, for user's input, except, UserInfo: Company & website

**Comment by brian9952** [comment]
DesignerInfo:
--- DesignerPrice
--- Rating
DesignerRating:
--- Rating
ChatSystem:
--- Timestamp
--- StatusMessage
UserPhoto:
--- PhotoName
DesignLikeCount:
--- Likes
UserExpo:
--- DatePurchased
UserInventory:
--- DatePurchased
DesignTransactionDetails
--- TransactionAmount
--- TransactionDate
--- ExpirationDate
--- DateCreated
DesignHeader
--- IsSold
ExpoTransactionHeader
--- isSuccess
--- isExpired
--- TransactionType
--- TicketQty
ExpoEvent
--- DateHeld
--- isOnline
ExpoEventPhoto
--- PhotoName
DesignDetails
--- DesignDateCreated
DesignCategories
--- CategoryName
--- CategoryDesc
DesignSubCategories
--- SubCategoryName
ExpoTransactionDetails
--- ExpoTransactionDate
--- ExpoExpirationDate
--- DateCreated
ExpoEventDetails
--- ExpoEventPlace
--- ExpoEventLink
DesignPhotos
--- DesignPhotoName
DesignFile
--- DesignFileName
--- DesignFileType

**Comment by brian9952** [comment]
not nulls added
