### ISSUE TITLE
cardinalities/multiplicity revision

### ISSUE THREAD

**Issue by brian9952** [felixfilipi/Beli-Desain#22]
User -> DesignerInfo: 1/1 (one to one)
User -> DesignerRating: 0..1/0..*
User -> ChatSystem: 0...*/0...*
User -> UserInfo: 1/1
User -> UserPhoto: 1/1
User -> UserFeedback: 0..*/1..*
User -> DesignerTransactionHeader: 0..*/1..*
User -> DesignLikeCount:
0...*/1..*
User -> UserExpo:
0...*/1...*
User -> DesignTransactionHeader:
0...*/1...*
User -> UserInventory:
0...*/1...*
User -> DesignHeader:
0...*/1...*
User -> ExpoTransactionHeader:
0...*/1...*
User -> ExpoEvent:
0...*/1...*
DesignerTransactionHeader -> DesignerTranscaionDetails:
1/1
DesignTransactionHeader -> DesignTranscationDetails:
1/1
DesignTranscationHeader -> UserInventory:
1/1
DesignHeader -> DesignTransactionHeader:
1/1
DesignHeader -> UserInventory:
1/1
DesignHeader -> DesignDetails:
1/1
DesignHeader -> DesignLikeCount:
1/0...*
ExpoTransactionHeader -> ExpoTransactionDetails:
1/1
ExpoEvent -> ExpoTransactionHeader:
1/1
ExpoEvent -> UserExpo:
1/0..*
ExpoEvent -> ExpoEventPhoto:
1/1
ExpoEvent -> ExpoEventDetails:
1/1
DesignDetails -> DesignPhotos:
1/1
DesignDetails -> DesignSpesification:
1...*/1
DesignDetails -> DesignFile:
1/1
DesignCategories -> DesignHeader:
1/1
DesignCategories -> DesignSubCategories
1...*/1
DesignSubCategories -> DesignHeader:
1/1
DesignSubCategories -> DesignTheme:
1...*/1
DesignTheme -> DesignHeader:
1/1

**Comment by brian9952** [comment]
User -> DesignerInfo: 1/1 (one to one)
User -> DesignerRating: 0..1/0..*
User -> ChatSystem: 0...*/0...*
User -> UserInfo: 1/1
User -> UserPhoto: 1/1
User -> UserFeedback: 0..*/1..*
User -> DesignerTransactionHeader: 0..*/1..*
User -> DesignLikeCount:
0...*/1..*
User -> UserExpo:
0...*/1...*
User -> DesignTransactionHeader:
0...*/1...*
User -> UserInventory:
0...*/1...*
User -> DesignHeader:
0...*/1...*
User -> ExpoTransactionHeader:
0...*/1...*
User -> ExpoEvent:
0...*/1...*
DesignerTransactionHeader -> DesignerTranscaionDetails:
1/1
DesignTransactionHeader -> DesignTranscationDetails:
1/1
DesignTranscationHeader -> UserInventory:
1/1
DesignHeader -> DesignTransactionHeader:
1/1
DesignHeader -> UserInventory:
1/1
DesignHeader -> DesignDetails:
1/1
DesignHeader -> DesignLikeCount:
1/0...*
ExpoTransactionHeader -> ExpoTransactionDetails:
1/1
ExpoEvent -> ExpoTransactionHeader:
1/1
ExpoEvent -> UserExpo:
1/0..*
ExpoEvent -> ExpoEventPhoto:
1/1
ExpoEvent -> ExpoEventDetails:
1/1
DesignDetails -> DesignPhotos:
1/1
DesignDetails -> DesignSpesification:
1.../1
DesignDetails -> DesignFile:
1/1
DesignCategories -> DesignHeader:
1/1
DesignCategories -> DesignSubCategories
1.../1
DesignSubCategories -> DesignHeader:
1/1
DesignSubCategories -> DesignTheme:
1...*/1
DesignTheme -> DesignHeader:
1/1

**Comment by brian9952** [comment]
x <---- many
User -> DesignerInfo: 1/1 (one to one)
User -> DesignerRating: 0..1/0..x
User -> ChatSystem: 0...x/0...x
User -> UserInfo: 1/1
User -> UserPhoto: 1/1
User -> UserFeedback: 0..x/1..x
User -> DesignerTransactionHeader: 0..x/1..x
User -> DesignLikeCount:
0...x/1..x
User -> UserExpo:
0...x/1...x
User -> DesignTransactionHeader:
0...x/1...x
User -> UserInventory:
0...x/1...x
User -> DesignHeader:
0...x/1...x
User -> ExpoTransactionHeader:
0...x/1...x
User -> ExpoEvent:
0...x/1...x
DesignerTransactionHeader -> DesignerTranscaionDetails:
1/1
DesignTransactionHeader -> DesignTranscationDetails:
1/1
DesignTranscationHeader -> UserInventory:
1/1
DesignHeader -> DesignTransactionHeader:
1/1
DesignHeader -> UserInventory:
1/1
DesignHeader -> DesignDetails:
1/1
DesignHeader -> DesignLikeCount:
1/0...x
ExpoTransactionHeader -> ExpoTransactionDetails:
1/1
ExpoEvent -> ExpoTransactionHeader:
1/1
ExpoEvent -> UserExpo:
1/0..x
ExpoEvent -> ExpoEventPhoto:
1/1
ExpoEvent -> ExpoEventDetails:
1/1
DesignDetails -> DesignPhotos:
1/1
DesignDetails -> DesignSpesification:
1...x/1
DesignDetails -> DesignFile:
1/1
DesignCategories -> DesignHeader:
1/1
DesignCategories -> DesignSubCategories
1...x/1
DesignSubCategories -> DesignHeader:
1/1
DesignSubCategories -> DesignTheme:
1...x/1
DesignTheme -> DesignHeader:
1/1

**Comment by felixfilipi** [comment]
done
